/**
 * Marketing Strategy Formatter for Obsidian Prospect Files
 * Converts AI-generated marketing strategies into readable Obsidian markdown
 */

import { MarketingStrategy, MarketingVector } from '../marketing/strategy-generator';
import { Logger } from '../logging';

export class MarketingStrategyFormatter {
  private logger: Logger;

  constructor() {
    this.logger = new Logger('MarketingStrategyFormatter', 'obsidian');
  }

  /**
   * Format marketing strategy as Obsidian markdown
   */
  formatStrategy(strategy: MarketingStrategy, businessName: string): string {
    try {
      return `
## 🚀 Digital Marketing Strategy

### Executive Summary
${strategy.executiveSummary}

### 📊 Industry Analysis
- **Market Size:** ${strategy.industryAnalysis.marketSize}
- **Average Revenue:** ${strategy.industryAnalysis.averageRevenue}
- **Profit Margins:** ${strategy.industryAnalysis.profitMargins}
- **Digital Spend:** ${strategy.industryAnalysis.digitalSpendPercentage}

#### Key Industry Trends
${strategy.industryAnalysis.keyTrends.map(trend => `- ${trend}`).join('\n')}

### 💼 Digital Marketing Plan
- **Priority Level:** ${this.formatPriority(strategy.digitalMarketingPlan.priorityLevel)}
- **Timeline:** ${strategy.digitalMarketingPlan.timeline}
- **Estimated Budget:** ${strategy.digitalMarketingPlan.estimatedBudget}
- **Expected ROI:** ${strategy.digitalMarketingPlan.expectedROI}

### 🎯 Marketing Strategies

${this.formatMarketingVectors(strategy.digitalMarketingPlan.strategies)}

### 🗓️ Implementation Roadmap

#### Phase 1: Foundation (Months 1-2)
${strategy.implementationRoadmap.phase1.map(item => `- [ ] ${item}`).join('\n')}

#### Phase 2: Growth (Months 3-6)
${strategy.implementationRoadmap.phase2.map(item => `- [ ] ${item}`).join('\n')}

#### Phase 3: Scale (Months 6-12)
${strategy.implementationRoadmap.phase3.map(item => `- [ ] ${item}`).join('\n')}

### 📈 Success Metrics
${strategy.successMetrics.map(metric => `- **${metric}**`).join('\n')}

---
*Marketing strategy generated by AI analysis • ${new Date().toLocaleDateString()}*
`;
    } catch (error) {
      this.logger.error('Failed to format marketing strategy', {
        error: error.message,
        businessName
      });
      return this.getErrorFallback();
    }
  }

  /**
   * Format individual marketing vectors
   */
  private formatMarketingVectors(vectors: MarketingVector[]): string {
    if (!vectors || vectors.length === 0) {
      return '*No specific marketing vectors available*';
    }

    return vectors.map(vector => this.formatSingleVector(vector)).join('\n\n');
  }

  /**
   * Format a single marketing vector
   */
  private formatSingleVector(vector: MarketingVector): string {
    return `#### ${vector.name} ${this.getPriorityEmoji(vector.priority)}

**Description:** ${vector.description}

**Implementation Steps:**
${vector.stepByStepPlan.map((step, index) => `${index + 1}. ${step}`).join('\n')}

**Investment Details:**
- **Estimated Cost:** ${vector.estimatedCost}
- **Timeframe:** ${vector.timeframe}
- **Priority:** ${this.formatPriority(vector.priority)}

**Expected Results:**
${vector.expectedResults.map(result => `- ${result}`).join('\n')}

**Recommended Tools:**
${vector.tools.map(tool => `- ${tool}`).join('\n')}`;
  }

  /**
   * Format priority with color coding
   */
  private formatPriority(priority: 'high' | 'medium' | 'low'): string {
    const priorityMap = {
      'high': '🔴 **HIGH**',
      'medium': '🟡 **MEDIUM**', 
      'low': '🟢 **LOW**'
    };
    return priorityMap[priority] || priority;
  }

  /**
   * Get priority emoji
   */
  private getPriorityEmoji(priority: 'high' | 'medium' | 'low'): string {
    const emojiMap = {
      'high': '🔥',
      'medium': '⭐',
      'low': '💡'
    };
    return emojiMap[priority] || '';
  }

  /**
   * Fallback content when formatting fails
   */
  private getErrorFallback(): string {
    return `
## 🚀 Digital Marketing Strategy

*Marketing strategy analysis is being processed. Please check back shortly.*

### Quick Wins Checklist
- [ ] Optimize Google Business Profile
- [ ] Set up basic SEO tracking
- [ ] Create social media presence
- [ ] Implement review management
- [ ] Develop content calendar

---
*Strategy generation in progress*
`;
  }

  /**
   * Create a compact strategy summary for prospect overview
   */
  formatStrategySummary(strategy: MarketingStrategy): string {
    try {
      const topStrategies = strategy.digitalMarketingPlan.strategies
        .filter(s => s.priority === 'high')
        .slice(0, 3)
        .map(s => s.name)
        .join(', ');

      return `**Marketing Opportunity:** ${strategy.digitalMarketingPlan.priorityLevel.toUpperCase()} priority • ${strategy.digitalMarketingPlan.estimatedBudget} budget • Focus: ${topStrategies || 'Digital transformation'}`;
    } catch (error) {
      return '**Marketing Opportunity:** Analysis pending';
    }
  }

  /**
   * Extract key marketing recommendations for next actions
   */
  extractActionableRecommendations(strategy: MarketingStrategy): string[] {
    try {
      const actions: string[] = [];
      
      // Get high-priority quick wins
      const highPriorityActions = strategy.digitalMarketingPlan.strategies
        .filter(s => s.priority === 'high')
        .slice(0, 2)
        .map(s => `Propose ${s.name} - ${s.description.toLowerCase()}`);
      
      actions.push(...highPriorityActions);

      // Add Phase 1 items as actionable recommendations
      if (strategy.implementationRoadmap.phase1.length > 0) {
        actions.push(`Discuss Phase 1 implementation: ${strategy.implementationRoadmap.phase1[0]}`);
      }

      // Add budget discussion
      actions.push(`Present marketing budget proposal: ${strategy.digitalMarketingPlan.estimatedBudget}`);

      return actions.slice(0, 4); // Limit to 4 actionable items
    } catch (error) {
      return ['Discuss digital marketing opportunities', 'Analyze current online presence'];
    }
  }
}